name: CI - GitCherryPick Frontend

on:
  push:
    branches: [main, 'sprint/**']
    paths:
      - 'gensoft_frontend/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main, 'sprint/**']
    paths:
      - 'gensoft_frontend/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd gensoft_frontend
          npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd gensoft_frontend
          npm install

      - name: Run ESLint
        run: |
          cd gensoft_frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd gensoft_frontend
          npm install

      - name: Run unit tests
        run: |
          cd gensoft_frontend
          npm test -- --coverage --watchAll=false --passWithNoTests

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: gensoft_frontend/coverage/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd gensoft_frontend
          npm install

      - name: Create environment file
        run: |
          cd gensoft_frontend
          echo "NEXT_PUBLIC_API_URL=http://localhost:3001" >> .env.local
          echo "NEXT_PUBLIC_SANDBOX_URL=http://localhost:8002" >> .env.local 
          echo "NEXT_PUBLIC_CONTENT_URL=http://localhost:8003" >> .env.local
          echo "NEXT_PUBLIC_APP_ENV=development" >> .env.local         
#Las declaraciones de sandbox y content, se pueden eliminar

      - name: Build application
        run: |
          cd gensoft_frontend
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: gensoft_frontend/.next/
          retention-days: 7

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #     - name: Checkout code
  #     uses: actions/checkout@v3

  #     - name: Deploy to staging
  #       run: |
  #         echo "🚀 Deploying to staging environment..."
  #         echo "Deployment would happen here with your specific deployment strategy"
